チェックアウト機能追加
bachikori/rails_ec pull request #5
Opened 2023-03-28 14:10 UTC by bachikori

## 課題のリンク

* https://github.com/happiness-chain/practice/blob/main/11_Ruby_on_Rails/001.2_rails%E3%81%A7EC%E3%82%B5%E3%82%A4%E3%83%88%E3%82%92%E4%BD%9C%E3%82%8B.md
## やったこと

* 購入機能を追加し購入者にメールを送信

## 動作確認方法

* 動作確認方法の手順を書いてください

## その他

* 購入処理を行ったあとどのテーブルを削除するのか曖昧だった

2023-03-28 22:37 UTC, ihatov08 commented on .rubocop.yml
> +  Enabled: false
これだと全ファイルで完全無効になるので、よろしくないですね。
数値を緩くするか(ex 20 -> 40)、局所的に無効にするかどちらかでお願いします。

2023-03-28 22:38 UTC, ihatov08 commented on app/controllers/customers_controller.rb
> +    current_cart.cart_items.delete_all
delete,delte_allはmodel callbackが無効になるので基本的に使わないようにお願いします！

2023-03-28 22:41 UTC, ihatov08 commented on app/models/cart.rb
> +  has_many :customers, dependent: :destroy
cartにひもづく購入者はひとりなので、has_manyな関連にはならないはずです！

2023-03-28 22:42 UTC, ihatov08 commented on config/routes.rb
> +  post 'customers/create'
こちらは不要に見えます。

2023-03-28 22:44 UTC, ihatov08 commented on app/controllers/customers_controller.rb
> +  def create
購入処理がcustomers#create(顧客を作成）するcontrollerなのは違和感があります。
order#create(注文の作成）などのほうがよいと思います。

2023-03-28 22:46 UTC, ihatov08 commented on app/controllers/customers_controller.rb
> +      delete_info(customer)
これだとcustomer.save,メールの送信、数量を減らす処理がまとめて行われることが担保されないので
(customer.saveだけ成功がありうる)、
save!などで例外をおこしつつ、transactionを使うようにお願いします！

2023-03-28 22:47 UTC, ihatov08 commented on app/controllers/customers_controller.rb
> +      flash[:error_messages] = customer.errors.full_messages
customerをインスタンス変数にして、
render :newなどすれば、
viewで`@customer.errors.messages`でエラーメッセージを表示できます。

2023-03-28 22:47 UTC, ihatov08 commented on app/models/customer.rb
> +class Customer < ApplicationRecord
customerよりorderが適切でしょう。

2023-03-28 22:49 UTC, ihatov08 commented on app/models/item.rb
> +    update(stock: stock - quantity)
これだとupdateに失敗しても気が付かなそうですね。
例外を起こすか、validationエラーを確認するようにしてください。

2023-03-30 06:06 UTC, bachikori commented on config/routes.rb
> +  post 'customers/create'
修正しました。

2023-03-30 06:06 UTC, bachikori commented on app/controllers/customers_controller.rb
> +  def create
修正しました。

2023-03-30 06:07 UTC, bachikori commented on app/models/customer.rb
> +class Customer < ApplicationRecord
修正しました。

2023-03-30 07:05 UTC, bachikori commented on app/controllers/customers_controller.rb
> +    current_cart.cart_items.delete_all
修正しました。

2023-03-30 09:13 UTC, bachikori commented on app/controllers/customers_controller.rb
> +      flash[:error_messages] = customer.errors.full_messages
修正しました。

2023-03-30 09:13 UTC, bachikori commented on .rubocop.yml
> +  Enabled: false
修正しました。

2023-03-30 09:51 UTC, bachikori commented on app/models/item.rb
> +    update(stock: stock - quantity)
修正しました。

2023-03-30 11:39 UTC, ihatov08 commented on .rubocop.yml
> +  Enabled: false
治っていないように見えます。

2023-03-30 11:39 UTC, ihatov08 commented on app/controllers/customers_controller.rb
> +  def create
こちらも治っていないように見えます

2023-03-30 11:41 UTC, ihatov08 commented
@bachikori 「修正しました」とコメントいただいていますが
修正がまったく反映されていないように見えます。

2023-03-30 12:19 UTC, bachikori commented on app/controllers/customers_controller.rb
> +  def create
修正が全て終わってからまとめてpushしようと思っていますので少々お待ちください。

2023-03-30 15:05 UTC, bachikori commented on app/models/cart.rb
> +  has_many :customers, dependent: :destroy
修正しました。

2023-03-30 15:06 UTC, bachikori commented on app/controllers/customers_controller.rb
> +      delete_info(customer)
上手くできているか分かりませんが修正しました！

2023-04-02 14:42 UTC, ihatov08 requested changes

2023-04-02 14:42 UTC, ihatov08 commented on app/controllers/orders_controller.rb
> +  # end
不要なコードはガシガシ削除しましょう！

2023-04-02 14:42 UTC, ihatov08 commented on app/controllers/orders_controller.rb
> +    current_cart.destroy
例外を起こさないとtransactionは機能しないのでdestroy!としてください！

2023-04-02 14:42 UTC, ihatov08 commented on app/models/item.rb
> +  def stock_dec(quantity)
例外が発生するメソッドは!をつけたほうがよいですね！

```suggestion
  def stock_dec!(quantity)
```

2023-04-02 14:42 UTC, ihatov08 commented on app/models/order.rb
> +  validates :card_cvv, presence: true
このあたりもemailであればemailの形式のvalidation,
番号系は数字や桁数のvalidationがほしいですね！

2023-04-03 11:32 UTC, bachikori commented on app/models/item.rb
> +  def stock_dec(quantity)
修正しました。

2023-04-03 11:34 UTC, bachikori commented on app/controllers/orders_controller.rb
> +  # end
修正しました。

2023-04-03 11:34 UTC, bachikori commented on app/models/order.rb
> +  validates :card_cvv, presence: true
修正しました。

2023-04-03 11:34 UTC, bachikori commented on app/controllers/orders_controller.rb
> +    current_cart.destroy
修正しました。

2023-04-03 14:07 UTC, ihatov08 approved these changes
ＬＧＴＭです、修正対応ありがとうございます！

2023-04-05 11:38 UTC, merged